name: gera_pix
description: "A new Flutter project."

publish_to: 'none' 


version: 1.1.11+15

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  
  vibration: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.3
  google_mobile_ads: ^5.2.0
  intl: ^0.20.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  diacritic: ^0.1.6
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: '#EEEEEE'
  android: true
  ios: true
  background_image: 'assets/splash.jpg'


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fontes/OFL.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baumans
      fonts:
        - asset: assets/fontes/Baumans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
